export const metadata = {
	title: "Dashboard | VoyageVibe",
	description: "Generated by Next.js",
};

export default function DashboardLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return <section>{children}</section>;
}
